name: Update Prices
on:
  schedule:
    - cron: '0 8 * * 1,4' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests beautifulsoup4
      - run: python update_db.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add products.json
          git commit -m "Update prices automatically" || echo "No changes to commit"
          git push
